### ISSUE TITLE
Link not working with JSX element

### ISSUE THREAD

**Issue by gtanchak** [webdevlapani/technical-queries#2]
### Whenever use JSX component as children in Link redirection is not working

```
<Link href="/">
       <GrinLogo />
</Link>
```

_I have used the Logo component inside the Link component but it is not redirecting._

**Comment by jenilmangukiya** [comment]
if you use Link that imported from next and you want to put inside it a html element or jsx element not a text. then you have to wrap html element or jsx element with default anchor tag.

```
<Link href="/">
  <a>
     <GrinLogo />
  </a>
</Link>
```

**Comment by gtanchak** [comment]
This solution is working for me

["next/link"](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag)

@jenilmangukiya Thanks!
